---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld
  labels:
    app: helloworld
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helloworld
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      serviceAccountName: helloworld
      volumes:
        - name: secrets-store-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "helloworld-aws-secrets"
      containers:
        - name: helloworld
          {{ if .Values.image }}
          image: "ironcore864/go-hello-http:{{ .Values.image.tag }}"
          {{ else }}
          image: "ironcore864/go-hello-http:{{ .Chart.AppVersion }}"
          {{ end }}
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: 250m
              memory: 128Mi
            requests:
              cpu: 250m
              memory: 128Mi
          envFrom:
            - secretRef:
                name: helloworld-secret
          volumeMounts:
            - name: secrets-store-inline
              mountPath: "/mnt/secrets-store"
              readOnly: true
