apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: helloworld-aws-secrets
spec:
  provider: aws
  secretObjects:
    - secretName: helloworld-secret
      type: Opaque
      data:
        - objectName: user
          key: NAME
        - objectName: pwd
          key: PASSWORD
  parameters:
    objects: |
      - objectName: "TestEnv/services/helloworld"
        objectType: "secretsmanager"
        jmesPath:
            - path: user
              objectAlias: user
            - path: pwd
              objectAlias: pwd
